name: Publish package to GitHub Packages
on:
  pull_request:
    types: [closed]
jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Publish package
        run: cd my-app && mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_VILLALTA }}

          