name: Publish package to GitHub Packages

on:
  push:
    branches:
      - feature/new-package  # Cambia a la rama que desees

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      JAVA_VERSION: 17

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Configure Maven
        run: |
          echo "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd\">
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>  # Usuario que hace el push
                <password>${{ secrets.GITHUB_TOKEN }}</password>  # Token de GitHub Actions
              </server>
            </servers>
          </settings>" > $HOME/.m2/settings.xml

      - name: Publish package
        run: mvn --batch-mode deploy
