name: Publish package

on:
  push:
    branches:
      - feature/python-try

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel

    - name: Build package
      run: python setup.py sdist bdist_wheel

    - name: Attempt to publish to GitHub Packages
      run: |
        echo "Publishing to GitHub Packages (this will fail)"
        # Simulate the publish command
        # Normally you would use:
        # python -m twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
        echo "This is where the package would be uploaded."
