name: Publish npm Package

on:
  push:
    branches:
      - feature/npm

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        registry-url: 'https://npm.pkg.github.com/@villalta'

    - name: npm login
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" > ~/.npmrc
        npm login --scope=@villalta --auth-type=legacy --registry=https://npm.pkg.github.com <<EOF
        alejandro-vn-jvillalta
        ${{ secrets.GH_TOKEN }}
        PUBLIC-EMAIL-ADDRESS
        EOF
        
    - name: Install dependencies
      run: npm install

    - name: Publish to GitHub Packages
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
