name: Publish npm Package

on:
  push:
    branches:
      - feature/npm

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        registry-url: 'https://npm.pkg.github.com/@villalta'
        cache: 'npm'

    - name: Configure npm for GitHub Packages
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" > ~/.npmrc
        echo "@villalta:registry=https://npm.pkg.github.com" >> ~/.npmrc
        echo "always-auth=true" >> ~/.npmrc

    - name: Install dependencies
      run: npm install

    - name: Publish to GitHub Packages
      run: npm publish
      env:
        NPM_CONFIG_TOKEN: ${{ secrets.GH_TOKEN }}
